version: '3.7'
services:
  ethereum:
    image: {DOCKER_IMAGE_TAG}
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile.alltools
    # container_name: ethereum-devnet
    # entrypoint: /entrypoint.sh
    ports:
      - '8545:8545'
      - '30303:30303'
    volumes:
      # - ./entrypoint.sh:/entrypoint.sh
      # - ./genesis.json:/genesis.json
      - ethereum_data:/tmp/geth
    # networks:
    #   - devnet
volumes:
  ethereum_data:
    driver: local
# networks:
#   devnet:
#     driver: bridge
