apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-ethereum-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-ethereum
  template:
    metadata:
      labels:
        app: go-ethereum
    spec:
      containers:
        - name: go-ethereum
          image: "kubemirchev/go-ethereum:latest"
          ports:
            - containerPort: 8545
            - containerPort: 30303
          env:
            - name: ETHEREUM_JSONRPC_HTTP_URL
              value: "http://127.0.0.1:8545"
            - name: ETHEREUM_NETWORK_NAME
              value: "devnet"
