apiVersion: v1
kind: Service
metadata:
  name: go-ethereum-service
spec:
  selector:
    app: go-ethereum
  ports:
    - name: rpc
      port: 8545
      targetPort: 8545
    - name: p2p
      port: 30303
      targetPort: 30303
  type: ClusterIP